name: Run Mahsa Config Script

on:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl

      - name: Run script
        env:
          MAHSA_API_TOKEN: ${{ secrets.MAHSA_API_TOKEN }}
          MAHSA_API_URL: ${{ secrets.MAHSA_API_URL }}
          CONFIGS_FILE: config.txt
          DELAY: "30"
          MAX_RUNTIME: "21000"
          ADS_URL: "🔥برای اتصال رایگان و با کیفیت آموزش های پین شده را چک کنید: https://t.me/DeltaKroneckerGithub"
        run: |
          sed -i 's/\r$//' scripts/add_configs.sh
          chmod +x scripts/add_configs.sh
          bash scripts/add_configs.sh || true

      - name: Commit and push changes
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          if [ -n "$(git status --porcelain config.txt)" ]; then
            git add config.txt
            git commit -m "chore: update config.txt [skip ci]"
            git push
          else
            echo "No changes to config.txt"
          fi
